workspace:
  base: /olog
  path: src/github.com/veiasai/olog

pipeline:
  build:
    image: veiasai/rdkafka:v2
    commands:
      - cd Conveyor
      - make
    volumes:
      - /tmp/cache:/cache

  script:
    image: python:2.7.15
    commands:
      - cd PythonScript
      - python generateData.py
      - ls /olog/src/github.com/veiasai/olog/PythonScript/DataDir
      - exit 0
    detach: true

  create_topic:
    image: java:8
    commands:
      - cd kafkaScript/bin
      - chmod -R 777 *
      - ./kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic br1000
      - ./kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic br1001
      - ./kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic br1002
      - ./kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic br1003
      - ./kafka-topics.sh --list --zookeeper zookeeper:2181

  consumer_0:
    group: consumer
    image:  jsenon/kafka-consumer:latest
    environment:
      - MY_KAFKABOOTSTRAP=kafka:9092 
      - MY_TOPIC=rb1000
      - MY_GROUPID=console-consumer
    detach: true

  consumer_1:
    image:  jsenon/kafka-consumer:latest
    environment:
      - MY_KAFKABOOTSTRAP=kafka:9092 
      - MY_TOPIC=rb1001
      - MY_GROUPID=console-consumer
    detach: true

  consumer_2:
    image:  jsenon/kafka-consumer:latest
    environment:
      - MY_KAFKABOOTSTRAP=kafka:9092 
      - MY_TOPIC=rb1002
      - MY_GROUPID=console-consumer
    detach: true

  consumer_3:
    image:  jsenon/kafka-consumer:latest
    environment:
      - MY_KAFKABOOTSTRAP=kafka:9092 
      - MY_TOPIC=rb1003
      - MY_GROUPID=console-consumer
    detach: true
    
  test:
    group: test
    image: veiasai/rdkafka:v2
    commands:
      - cd Conveyor
      - timeout 60 ./conveyor || echo timeout
      - timeout 60 ./conveyor || echo recover_1_timeout
      - timeout 60 ./conveyor || echo recover_2_timeout
      - exit 0

services: 
  zookeeper:
    image: zookeeper:3.4

  kafka:
    image:  digitalwonderland/kafka:latest
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true


# workspace:
#   base: /olog
#   path: src/github.com/veiasai/olog

# pipeline:
#   streambuild:
#     image: maven:alpine
#     commands:
#       - cd kafka-stream
#       - mvn package assembly:assembly
#     volumes:
#       - /home/drone/maven-repo:/root/.m2

#   build:
#     image: gcc
#     commands:
#       - cp fluent-bit/*.conf /cache
#       - cd rdkafka
#       - make
#     volumes:
#       - /tmp/cache:/cache

#   script:
#     image: python:2.7.15
#     commands:
#       - cd PythonScript
#       - python generateData.py
#       - ls /olog/src/github.com/veiasai/olog/PythonScript/DataDir
#       - exit 0
#     detach: true

#   fluent:
#     image: fluent/fluent-bit:1.0
#     volumes:
#       - /tmp/cache/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
#       - /tmp/cache/parsers.conf:/fluent-bit/etc/parsers.conf
#     detach: true

#   # streamconsumer:
#   #   image:  jsenon/kafka-consumer:latest
#   #   environment:
#   #     - MY_KAFKABOOTSTRAP=kafka:9092 
#   #     - MY_TOPIC=demo-count-output  
#   #     - MY_GROUPID=stream-consumer
#   #   detach: true


#   test:
#     group: test
#     image: gcc
#     commands:
#       - cd rdkafka
#       - cp link_lib/* /usr/lib/
#       - ln -s /usr/lib/libjsoncpp.so.0.10.6 /usr/lib/libjsoncpp.so.0
#       - timeout 240 ./monitor
#       - exit 0

#   # streamtest:
#   #   group: test
#   #   image: veiasai/java:8
#   #   commands:
#   #     - cd kafka-stream
#   #     - timeout 60 java -jar target/KafkaStreamsDemo-1.0-SNAPSHOT-jar-with-dependencies.jar
#   #     - exit 0

#   mpublish:
#     group: test
#     image: plugins/docker
#     repo: veiasai/kafka-monitor
#     tags: ["latest"]
#     secrets: [ docker_username, docker_password ]
#     dockerfile: MonitorDockerfile
#     when:
#       branch: master

#   # spublish:
#   #   group: test
#   #   image: plugins/docker
#   #   repo: veiasai/kafka-stream-monitor
#   #   tags: ["latest"]
#   #   secrets: [ docker_username, docker_password ]
#   #   dockerfile: StreamDockerfile
#   #   when:
#   #     branch: master


